Users
FelixGustafsson/art-auction-backend pull request #3
Opened 2024-04-15 13:36 UTC by EricPudney

[added encryption to users.api, renamed models consistently]

2024-04-15 13:43 UTC, FelixGustafsson commented on api/users.js
We should send statuscodes along with the response for better errorhandling.

2024-04-15 13:45 UTC, FelixGustafsson requested changes
We should send statuscodes along with the response for better errorhandling. (api/users.js)

2024-04-15 13:59 UTC, EricPudney commented on api/users.js
absolut, jag fixar imorgon

2024-04-16 07:14 UTC, EricPudney commented on api/users.js
jag tror det blir bra nu.

2024-04-17 06:47 UTC, FelixGustafsson approved these changes

2024-04-18 06:26 UTC, VeroniccaStrand approved these changes

2024-04-18 06:26 UTC, merged